### PR TITLE
#fix for DEVEP-734

### PR DESCRIPTION
**Pull request by kgera**
Correcting the anchor link for issue:  https://jira.corp.adobe.com/browse/DEVEP-734

### CODE REVIEW

**Comment by kgera** [comment]
@MattLusher  can you merge the second commit on PR now?

**Comment by kgera** [comment]
@MattLusher please review and merge commit 964cfdcb1dca14fa32af2b91ed27b40be3b76ef9

**Comment by kgera** [comment]
@MattLusher  No worries. Please check now.

**Comment by MattLusher** [comment]
@kgera Thanks, Kanika! PR merged.

**Pull request merged**
